modules:
  - name: slide
    type: SlideImporter
    group: default
    parameters:
      filename: adjusted

  - name: markers
    type: MarkersImporter
    group: default
    parameters:
      filename: markers

  - name: fragmentator
    type: Fragmentator
    group: default
    depends_on:
      - slide
    parameters:
      step: 16

  - name: labeler
    type: Labeler
    group: default
    depends_on:
      - slide
      - markers
      - fragmentator
    parameters:
      margin: 8

  - name: labeler-exporter
    type: Exporter
    group: default
    depends_on:
      - labeler
    parameters:
      filename: labels-f96-s16-m8


groups:
  - name: default
    options:
      replicas: 8


shared_parameters:
  source: data/source
  target: data/results
  experiments: data/experiments
  fragment: 96
