modules:
  - name: slide
    type: SlideImporter
    group: default
    parameters:
      filename: adjusted

  - name: labeler-importer
    type: LabelerImporter
    group: default
    parameters:
      filename: labels-f96-s16-m8
      margin: 8

  - name: cnn
    type: CNN
    group: default
    depends_on:
      - slide
      - labeler-importer
    parameters:
      model: data/experiments/densenet121-f96-s96-m8-rgb/Amy/weights.hdf5

  - name: prediction-exporter
    type: Exporter
    group: default
    depends_on:
      - cnn
    parameters:
      filename: predictions-f96-s16-m8-amy

groups:
  - name: default
    options:
      replicas: 2
      num_gpus: 1


shared_parameters:
  source: data/source
  target: data/results
  experiments: data/experiments
  fragment: 96
