modules:
  - name: prediction-amy
    type: PredictionImporter
    group: default
    parameters:
      filename: predictions-f96-s16-m8-amy

  - name: prediction-ben
    type: PredictionImporter
    group: default
    parameters:
      filename: predictions-f96-s16-m8-ben

  - name: prediction-charlie
    type: PredictionImporter
    group: default
    parameters:
      filename: predictions-f96-s16-m8-charlie

  - name: prediction-ensemble
    type: EnsemblePredictions
    group: default
    depends_on:
      - prediction-amy
      - prediction-ben
      - prediction-charlie
    parameters:
      classifiers:
        prediction-amy: amy
        prediction-ben: ben
        prediction-charlie: charlie

  - name: prediction-exporter
    type: Exporter
    group: default
    depends_on:
      - prediction-ensemble
    parameters:
      filename: predictions-f96-s16-m8-ensemble

groups:
  - name: default
    options:
      replicas: 8


shared_parameters:
  source: data/source
  target: data/results
  experiments: data/experiments
  fragment: 96
