version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: ki67-research:latest
    container_name: ki67-research
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    volumes:
      - .:/workspace/ki67
