modules:
  - name: prediction-amy
    type: PredictionImporter
    group: default
    parameters:
      filename: predictions-f${size}-s${stride}-m${margin}-amy

  - name: prediction-ben
    type: PredictionImporter
    group: default
    parameters:
      filename: predictions-f${size}-s${stride}-m${margin}-ben

  - name: prediction-charlie
    type: PredictionImporter
    group: default
    parameters:
      filename: predictions-f${size}-s${stride}-m${margin}-charlie

  - name: prediction-ensemble
    type: EnsemblePredictions
    group: default
    depends_on:
      - prediction-amy
      - prediction-ben
      - prediction-charlie
    parameters:
      classifiers:
        prediction-amy: amy
        prediction-ben: ben
        prediction-charlie: charlie

  - name: prediction-exporter
    type: Exporter
    group: default
    depends_on:
      - prediction-ensemble
    parameters:
      filename: predictions-f${size}-s${stride}-m${margin}-ensemble

groups:
  - name: default
    options:
      replicas: 8


shared_parameters:
  source: data/source
  target: data/results
  fragment: ${size}
