modules:
  - name: slide
    type: SlideImporter
    group: default
    parameters:
      filename: adjusted

  - name: markers
    type: MarkersImporter
    group: default
    parameters:
      filename: markers

  - name: fragmentator
    type: Fragmentator
    group: default
    depends_on:
      - slide
    parameters:
      step: ${stride}

  - name: labeler
    type: Labeler
    group: default
    depends_on:
      - slide
      - markers
      - fragmentator
    parameters:
      margin: ${margin}

  - name: labeler-exporter
    type: Exporter
    group: default
    depends_on:
      - labeler
    parameters:
      filename: labels-f${size}-s${stride}-m${margin}


groups:
  - name: default
    options:
      replicas: 8


shared_parameters:
  source: data/source
  target: data/results
  fragment: ${size}
