modules:
  - name: slide
    type: SlideImporter
    group: default
    parameters:
      filename: adjusted

  - name: markers
    type: MarkersImporter
    group: default
    parameters:
      filename: markers

  - name: fragmentator-s96
    type: Fragmentator
    group: default
    depends_on:
      - slide
    parameters:
      step: 96

  - name: labeler-s96-m16
    type: Labeler
    group: default
    depends_on:
      - slide
      - markers
      - fragmentator-s96
    parameters:
      margin: 16

  - name: labeler-s96-m16-exporter
    type: Exporter
    group: default
    depends_on:
      - labeler-s96-m16
    parameters:
      filename: labels-f192-s96-m16

  - name: examples-builder
    type: ExamplesBuilder
    group: default
    depends_on:
      - slide
      - labeler-s96-m16
    parameters:
      filename: examples-f192-s96-m16


groups:
  - name: default
    options:
      replicas: 8


shared_parameters:
  source: data/source
  target: data/results
  fragment: 192
