modules:
  - name: slide
    type: SlideImporter
    group: default
    parameters:
      filename: adjusted

  - name: markers
    type: MarkersImporter
    group: default
    parameters:
      filename: markers

  - name: fragmentator
    type: Fragmentator
    group: default
    depends_on:
      - slide
    parameters:
      step: ${training_stride}

  - name: labeler
    type: Labeler
    group: default
    depends_on:
      - slide
      - markers
      - fragmentator
    parameters:
      margin: ${margin}

  - name: examples-builder
    type: ExamplesBuilder
    group: default
    depends_on:
      - slide
      - labeler
    parameters:
      filename: examples-f${size}-s${training_stride}-m${margin}


groups:
  - name: default
    options:
      replicas: 2


shared_parameters:
  source: data/source
  target: data/results
  fragment: ${size}
