modules:
  - name: slide
    type: SlideImporter
    group: default
    parameters:
      filename: adjusted

  - name: markers
    type: MarkersImporter
    group: default
    parameters:
      filename: markers

  - name: fragmentator
    type: Fragmentator
    group: default
    depends_on:
      - slide
    parameters:
      step: 96

  - name: labeler
    type: Labeler
    group: default
    depends_on:
      - slide
      - markers
      - fragmentator
    parameters:
      margin: 8

  - name: examples-builder
    type: ExamplesBuilder
    group: default
    depends_on:
      - slide
      - labeler
    parameters:
      filename: examples-f96-s96-m8


groups:
  - name: default
    options:
      replicas: 8


shared_parameters:
  source: data/source
  target: data/results
  fragment: 96
