modules:
  - name: slide
    type: SlideImporter
    group: default
    parameters:
      filename: base

  - name: prediction
    type: PredictionImporter
    group: default
    parameters:
      filename: predictions-f${size}-s${stride}-m${margin}-${model}

  # Fuzzy Mask
  - name: fuzzy-mask
    type: Fuzzificator
    group: default
    depends_on:
      - slide
      - prediction

  - name: fuzzy-mask-exporter
    type: Exporter
    group: default
    depends_on:
      - fuzzy-mask
    parameters:
      filename: fuzzy-mask-f${size}-${model}

  - name: fuzzy-mask-roi-preview
    type: MaskRoiPreview
    group: default
    depends_on:
      - slide
      - fuzzy-mask

  - name: fuzzy-mask-roi-preview-exporter
    type: Exporter
    group: default
    depends_on:
      - fuzzy-mask-roi-preview
    parameters:
      filename: preview-fuzzy-mask-f${size}-${model}

  # Crips Mask
  - name: crisp-mask
    type: Defuzzificator
    group: default
    depends_on:
      - fuzzy-mask
    parameters:
      kernel: ${mask_kernel}
      min_area: ${min_area}
      threshold: 0.5

  - name: crisp-mask-exporter
    type: Exporter
    group: default
    depends_on:
      - crisp-mask
    parameters:
      filename: crisp-mask-f${size}-${model}

  - name: crisp-mask-roi-preview
    type: MaskRoiPreview
    group: default
    depends_on:
      - slide
      - crisp-mask

  - name: crisp-mask-roi-preview-exporter
    type: Exporter
    group: default
    depends_on:
      - crisp-mask-roi-preview
    parameters:
      filename: preview-crisp-mask-f${size}-${model}

groups:
  - name: default
    options:
      replicas: 2


shared_parameters:
  source: data/source
  target: data/results
  fragment: ${size}
