modules:
  - name: slide
    type: SlideImporter
    group: default
    parameters:
      filename: base

  - name: crisp-mask
    type: MaskImporter
    group: default
    parameters:
      filename: crisp-mask-f${size}-${model}

  - name: cells
    type: Segmentator
    group: default
    depends_on:
      - slide
      - crisp-mask
    parameters:
      min_area: 144
      threshold_positive: ${threshold_positive}
      threshold_relevant: ${threshold_relevant}

  - name: cells-exporter
    type: Exporter
    group: default
    depends_on:
      - cells
    parameters:
      filename: biased-cells-f${size}-${model}

  - name: preview
    type: CellsPreview
    group: default
    depends_on:
      - slide
      - cells

  - name: cells-preview-exporter
    type: Exporter
    group: default
    depends_on:
      - preview
    parameters:
      filename: preview-biased-cells-f${size}-${model}


groups:
  - name: default
    options:
      replicas: 8


shared_parameters:
  source: data/source
  target: data/results
  fragment: ${size}
