modules:
  - name: splitter
    type: Splitter
    parameters:
      testing: 20
      shards:
        - amy
        - ben
        - charlie
      experiments: data/experiments

shared_parameters:
  source: data/source
  target: data/results
  fragment: ${size}
